// Render article charts at phone width; PNG text is deterministic, not generated by AI.
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const modulePath=process.env.MO_PLAYWRIGHT_MODULE || '/Users/olivialee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const {chromium}=await import(modulePath);
const h=import.meta.dirname,a=path.resolve(h,'../assets/v13'),i=path.join(a,'images');
await fs.mkdir(i,{recursive:true});
await fs.copyFile(path.resolve(h,'../../../assets/brand/2026-09-12-header-v2/03-retro-terminal.png'),path.join(i,'01-header.png'));
await fs.copyFile(path.join(a,'originals/computing-lab.png'),path.join(i,'02-computing-lab.png'));
await fs.copyFile(path.join(a,'originals/robot-lab.png'),path.join(i,'13-robot-lab.png'));
const browser=await chromium.launch({executablePath:process.env.MO_CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:366,height:900},deviceScaleFactor:3});
const files=(await fs.readdir(path.join(a,'cards'))).filter(x=>x.endsWith('.html')).sort();
const manifest=[];
for(const f of files){
 await page.goto(pathToFileURL(path.join(a,'cards',f)).href);await page.evaluate(()=>document.fonts.ready);
 await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(x=>x.decode())));
 if(await page.evaluate(()=>document.documentElement.scrollWidth>366))throw Error('Overflow: '+f);
 const el=page.locator('main');const b=await el.boundingBox();
 await el.screenshot({path:path.join(i,f.replace('.html','.png'))});
 manifest.push({file:f.replace('.html','.png'),cssWidth:b.width,cssHeight:b.height,pixelWidth:b.width*3,pixelHeight:Math.round(b.height*3),text:await el.innerText()});
}
await fs.writeFile(path.join(a,'render-check.json'),JSON.stringify(manifest,null,2));
// Contact sheet retains uncropped official originals for visual identity checks.
const gallery=`<!doctype html><meta charset="utf-8"><style>body{margin:0;font-family:Arial;background:#e9eee9}.g{display:grid;grid-template-columns:repeat(3,400px);gap:12px;padding:12px}.item{background:white}img{width:400px;display:block}p{margin:8px}</style><div class="g">${['rtx5090','rtxpro6000','dgxspark','gb200','jetson','drive'].map(k=>`<div class="item"><img src="${pathToFileURL(path.join(a,'originals',k+'.jpg')).href}"><p>${k}</p></div>`).join('')}</div>`;
await page.setViewportSize({width:1248,height:1000});await page.setContent(gallery);await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(x=>x.decode())));await page.screenshot({path:'/tmp/v13-official-contact.png',fullPage:true});
await browser.close();console.log('Rendered '+files.length+' cards');
